### PR TITLE
Fix dragging when reordering rows

### LINKED ISSUE #225: Dragging to fill down redirects Mac OS Firefox to dummy.com

### PR DESCRIPTION
**Pull request by willgates**
## Description
This PR fixes the bug that when reordering rows, the rows in between the start and destination of the reordering are updated (depending on which cell/column was selected before the reorder). It also fixes #225.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Select a cell other than the drag handler (so not the first column). When reordering a row, the column of the selected cell will be copied for all rows between the row's original position and the new position.

**What is the new behavior?**
The row changes position because of the reorder but no values/columns are overwritten.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by diogofcunha** [comment]
Hey pal, can you check the builds?

File: src/ReactDataGrid.js [hunk 1]
```diff
@@ -322,15 +317,17 @@ const ReactDataGrid = React.createClass({
 
   onDragStart(e: SyntheticEvent) {
     let idx = this.state.selected.idx;
-    if (idx > -1) {
+    // To prevent dragging down/up when reordering rows.
+    const isDragging = e && e.target && e.target.className;
```
Comment (diogofcunha) [inline src/ReactDataGrid.js]: when we are dragging rows using react-dnd we are also dragging, can this change to for example `isViewportDrag`

File: src/ReactDataGrid.js [hunk 2]
```diff
@@ -369,33 +366,37 @@ const ReactDataGrid = React.createClass({
     }
   },
 
+  isCellWithinBounds(cell) {
```
Comment (diogofcunha) [inline src/ReactDataGrid.js]: FYI you can make this simpler with ES6.

Using object destructuring in the params.

```
isCellWithinBounds({ idx, rowIdx }) {
   return idx >= 0
      && rowIdx >= 0
      && idx < ColumnUtils.getSize(this.state.columnMetrics.columns)
      && rowIdx < this.props.rowsCount;
}
```

File: src/ReactDataGrid.js [hunk 3]
```diff
@@ -369,33 +366,37 @@ const ReactDataGrid = React.createClass({
...
-    let cellKey = this.getColumn(this.state.selected.idx).key;
-    let fromRow = selected.rowIdx < dragged.overRowIdx ? selected.rowIdx : dragged.overRowIdx;
-    let toRow   = selected.rowIdx > dragged.overRowIdx ? selected.rowIdx : dragged.overRowIdx;
-    if (this.props.onCellsDragged) {
-      this.props.onCellsDragged({cellKey: cellKey, fromRow: fromRow, toRow: toRow, value: dragged.value});
-    }
-
-    if (this.props.onGridRowsUpdated) {
-      this.onGridRowsUpdated(cellKey, fromRow, toRow, {[cellKey]: dragged.value}, AppConstants.UpdateActions.CELL_DRAG);
+    const selected = this.state.selected;
```
Comment (diogofcunha) [inline src/ReactDataGrid.js]: using es6, `const { selected, dragged } = this.state;`

File: src/ReactDataGrid.js (hunk 2 above)
Comment (willgates) [inline src/ReactDataGrid.js]: 👍
